### ISSUE TITLE
Im having an issue with the Vec3 in 1.8.8!

### ISSUE THREAD

**Issue by seanfilimon** [Its-its/CannoningUtils#1]
Project.java: (lines 57 - 78)
`			
if (Keyboard.isKeyDown(Keyboard.KEY_LSHIFT)) {
				for (int i = 0; i < this.shots.length; i++) {
					Vec3 pos = this.shots[i].position;
					if(shots.compareTo(pos) == 0) {
						this.shots = ArrayUtils.remove(this.shots, i);
						break returnz;
					}
				}
`

Error Msg: The method compareTo(Vec3i) in the type Vec3i is not applicable for the arguments (Vec3)
https://gyazo.com/2e866f47e6d5b03a52ca9b85d34b4d14
how do I fix this issue ? and Why are you comparing apples to oranges in this?

**Comment by seanfilimon** [comment]
@Its-its

**Comment by Its-its** [comment]
I honestly don't remember anything I did with this. I personally haven't touched Java in years.

I don't think I even finished that "Projection.java" class.

**Comment by Its-its** [comment]
Yea, to add to that it looks like you can remove the "Projection.java" and "EntityDummyTNT.java" class. I never actually finished it.

**Comment by seanfilimon** [comment]
ok Thank you

**Comment by seanfilimon** [comment]
If your wondering what im doing Im converting your mod to forge 1.8.8 and adding tnt detection and some other features
